version: "3.7"

services:
  point-rating-system:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: point-rating-system
    ports:
      - 3004:3004
      - 4004:4004
    volumes:
      - service:/di
    depends_on:
      - mongodb
    networks:
      - point-rating-network
  mongodb:
    container_name: mongo_rating
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 3307:27017
    volumes:
      - db-data-rating:/data/db
    networks:
      - point-rating-network
volumes:
  db-data-rating:
  service:
networks:
  point-rating-network:
    name: point-network
