version: "3.7"

services:
  mongodb:
    container_name: mongo_rating
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 3307:27017
    volumes:
      - db-data-rating:/data/db
    networks:
      - point-rating-network
volumes:
  db-data-rating:
networks:
  point-rating-network:
    name: point-rating-network-dev
