version: "3.7"

services:
  mongodb:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - db-data-order:/data/db
    networks:
      - elearning-network
volumes:
  db-data-order:
networks:
  point-training-network:
    name: ${NETWORK_NAME}
