apiVersion: v1
kind: Secret
metadata:
  name: thl-khoaluan-qldrl-secret
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQDE5Mi4xNjguNTAuMTUyOjMzMDcvaW52ZW50b3J5P2F1dGhTb3VyY2U9YWRtaW4=
